version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./:/var/www/html/
    networks:
      - backend
    working_dir: /var/www/html/
    tty: true
    container_name: app
    env_file:
      - .env

networks:
  backend:
    driver: bridge