name: C.I

on:
  pull_request:
    branches:
      - main
      - feature/*
      - hotfix/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: python -m unittest

      - name: Run Mypy Type Linter
        run: mypy src/ test/